### ISSUE TITLE
the permission zschedulers.list is not working, at least for me

### ISSUE THREAD

**Issue by MatiasVME** [Maxlego08/zSchedulers#3]
If I run /sch list  not work for the no-OPs players

**Comment by EnzoShoes** [comment]
The documentation indeed doesn't seem to match the code. Either way, according to the code, in the current version, the permissions are actually:
- schedulers.reload
- schedulers.list
- schedulers.use

so basically just without the z.
Keep in mind this might change in the future if @Maxlego08 decides they should be changed.
